apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak-ispn.fullname" . }}-imported-realms
  labels:
    {{- include "keycloak-ispn.labels" . | nindent 4 }}
data:
{{- $files := .Files.Glob "realms/*" }}
{{- range $path, $file := $files }}
  {{ base $path }}: |-
{{ $file | toString | indent 4 }}
{{- end }}
---