{{- if .Values.ispn.identitiesBatch }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-ispn.fullname" . }}-identities-batch
  labels:
    {{- include "keycloak-ispn.labels" . | nindent 4 }}
type: Opaque
data:
  identities-batch: {{ .Values.ispn.identitiesBatch | b64enc }}
{{- end }}